config/routes.rb
Rails.application.routes.draw do
  get 'reports/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
  resources :users do
    member do 
      get :bookmarks
    end
  end
  
  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :reports, only: [:new, :create]
  resources :picture_details, only: [:index, :new, :create]
  resources :categories, only: [:new, :show, :create]
  resources :areas, only: [:new, :show, :create]
  resources :bookmarks, only: [:index, :create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, dependent: :destroy
  mount_uploader :picture, PictureUploader
  validates :title, presence: true, length: { maximum: 30 }
  validates :detail, presence: true, length: { maximum: 300 }
  validates :picture, presence: true
  validate :picture_size
  has_many :picture_details, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmark, dependent: :destroy
  has_many :post_category_relations, dependent: :destroy
  has_many :categories, through: :post_category_relations
  has_many :post_category_area_relations, dependent: :destroy
  has_many :area, through: :post_category_area_relations
  geocoded_by :address, latitude: :latitude, longitude: :longitude
  after_validation :geocode, if: :address_changed?

  accepts_nested_attributes_for :post_category_relations, allow_destroy: true

  private
  
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "ファイルサイズを5MB以下にしてください。")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in,  only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @post = current_user.posts.build
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.all
    @pictures = @post.picture_details.order(id: :desc)
    results = Geocoder.search(params[:address])
    @comment = Comment.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    @categories = Category.all
    if @post.save
      flash[:success] = '釣果を投稿しました。'
      redirect_to root_url
    else
      @posts = current_user.posts.order(id: :desc).page(params[:page])
      @categories = Category.all
      flash.now[:danger] = '釣果の投稿に失敗しました。'
      render 'posts/new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "更新しました。"
      redirect_to @post
    else
      flash.now[:danger] = "更新できませんでした。"
      redirect_to edit_post_path
    end
  end
  
  def destroy
    @post.destroy
    flash[:success] = '投稿を削除しました。'
    redirect_to root_url
  end
  
  def map
    results = Geocoder.search(params[:address])
    @latlng = results.first.coordinates
    
    respond_to do |format|
      format.js
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :detail, :picture, :weather, :address, :temperature, :time_zone, :how_to_fish, :fish_caught, category_ids: [], area_ids: [])
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_contents.html.erb
<h1><%= @post.title %></h1>

<ul class="bxslider">
    <li><%= image_tag @post.picture.url %></li>
  <% @pictures.each do |picture| %>
    <li><%= image_tag picture.image1.url if picture.image1? %></li>
  <% end %>
</ul>
<h3>釣果詳細</h3>
<table class="table">
  <tbody>
    <tr>
      <th><i class="fas fa-sun"></i>天気</th>
      <td><%= @post.weather %></td>
    </tr>
    <tr>
      <th><i class="fas fa-temperature-high"></i>気温</th>
      <td><%= @post.temperature %></td>
    </tr>
    <tr>
      <th><i class="far fa-clock"></i>時間帯</th>
      <td><%= @post.time_zone %></td>
    </tr>
    <tr>
      <th><i class="fas fa-map-marker-alt"></i>釣れた場所</th>
      <td><%= @post.address %></td>
    </tr>
    <tr>
      <th><i class="fas fa-male"></i>釣り方</th>
      <td><%= @post.how_to_fish %></td>
    </tr>
    <tr>
      <th><i class="fas fa-fish"></i>釣れた魚</th>
      <td><%= @post.fish_caught %></td>
    </tr>
    <tr>
      <th><i class="fas fa-file-alt"></i>釣行レポート</th>
      <td><%= @post.detail %></td>
    </tr>
  </tbody>
</table>
<div class="map">
  <h3>釣行場所</h3>
  <div id="map">
  </div>
  <script>
  function initMap(){
    let map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: <%= @post.latitude %>, lng: <%= @post.longitude %> },
    zoom: 15
    });
  }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap" async defer></script>
</div>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
  <li class="card">
    <div class="card-header">
      <h4><%= link_to "#{post.title}", post_path(post) %></h4>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-4">
          <img src="<%= post.picture.url %>" class="img-fluid">
        </div>
        <div class="col-8">
          <div class="item1">
          <%= post.detail %>
          </div>
          <div class="item2">
            <img class="mr-2 rounded" src="<%= gravatar_url(post.user, { size: 30 }) %>" alt="">
            <%= link_to post.user.name, user_path(post.user) %> <span class="text-muted small">投稿日 <%= post.created_at %></span>
          </div>
        </div>
      </div>
    </div>
  </li>
<% end %>
<%#= paginate @posts %>
      

app/views/posts/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= form_for(@post) do |f| %>
    <div class="form-group">
      <%= f.label :title, 'タイトル' %>
      <%= f.text_area :title, class: 'form-control', rows: 2 %>
    </div>
    
    <div class="form-group">
      <%= f.label :detail, '内容' %>
      <%= f.text_area :detail, class: 'form-control', rows: 5 %>
    </div>
    
    <div class="form-group">
      <%= f.label :address, '釣行場所' %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :weather, '天気' %>
      <%= f.select :weather,["晴れ", "曇り", "雨" ], {},   class: 'form-control' %>
    </div>
    
    <div class="form-group">    
      <%= f.label :temperature, '気温' %>
      <%= f.select :temperature,["0~5℃", "6~10℃", "11~15℃", "16~20℃", "21~25℃", "26~30℃", "31~35℃" ], {},   class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :time_zone, '時間帯' %>
      <%= f.select :time_zone,["朝", "昼", "夕方", "夜" ], {},   class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :how_to_fish, '釣り方' %>
      <%= f.text_field :how_to_fish, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :fish_caught, '釣れた魚' %>
      <%= f.text_field :fish_caught, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :category, '魚種カテゴリ' %>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
        <%= category.label do %>
          <%= category.check_box %>
          <%= category.text %>
        <% end %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :area, 'エリアカテゴリ' %>
      <%= f.collection_check_boxes(:area_ids, Area.all, :id, :name, include_hidden: false) do |area| %>
        <%= area.label do %>
          <%= area.check_box %>
          <%= area.text %>
        <% end %>
      <% end %>
    </div>
    
    <div class="form-group">
      <%= f.submit "釣果を更新する", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<aside class="col-sm-4">
  <%= form_with(model: @post, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="form-group">
      <%= f.label :title, 'タイトル' %>
      <%= f.text_area :title, class: 'form-control', rows: 2 %>
    </div>
    
    <div class="form-group">
      <%= f.label :detail, '釣行レポート' %>
      <%= f.text_area :detail, class: 'form-control', rows: 5 %>
    </div>
    
    <div class="form-group">
      <%= f.label :address, '釣行場所' %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :weather, '天気' %>
      <%= f.select :weather,["晴れ", "曇り", "雨" ], {},   class: 'form-control' %>
    </div>
    
    <div class="form-group">    
      <%= f.label :temperature, '気温' %>
      <%= f.select :temperature,["0~5℃", "6~10℃", "11~15℃", "16~20℃", "21~25℃", "26~30℃", "31~35℃" ], {},   class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :time_zone, '時間帯' %>
      <%= f.select :time_zone,["朝", "昼", "夕方", "夜" ], {},   class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :how_to_fish, '釣り方' %>
      <%= f.text_field :how_to_fish, class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :fish_caught, '釣れた魚' %>
      <%= f.text_field :fish_caught, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :picture, 'タイトル画像' %>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'  %>
    </div>
    
    <%= f.label :category, '魚種カテゴリ' %>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name, include_hidden: false) do |category| %>
      <%= category.label do %>
        <%= category.check_box %>
        <%= category.text %>
      <% end %>
    <% end %>

    <%= f.label :area, 'エリアカテゴリ' %>
    <%= f.collection_check_boxes(:area_ids, Area.all, :id, :name, include_hidden: false) do |area| %>
      <%= area.label do %>
        <%= area.check_box %>
        <%= area.text %>
      <% end %>
    <% end %>
    <%= f.submit '釣果を投稿する', class: 'btn btn-primary btn-block' %>
  <% end %>
        
  <script type="text/javascript">
    $('#post_picture').bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('ファイルの最大サイズは5MBです。ファイルサイズを変更してください。');
      }
    });
  </script>
</aside>

app/views/posts/show.html.erb
<div class="bookmark-content">
  <%= render 'bookmarks/contents' %>
</div>

<div class="post-content">
  <%= render 'posts/contents' %>
</div>

<div class="comments">
  <%= render 'comments/contents' %>
</div>

<div class="text-right">
  <% if current_user?(@post.user) %>
    <div class="form-group">
      <%= link_to '画像追加', new_picture_detail_path(id: @post.id), class: 'btn btn-success' %>
      <%= link_to '編集', edit_post_path(@post), class: 'btn btn-success' %>
    </div>
    <div class="form-group text-right">
      <%= link_to "削除",@post, method: :delete, data: { confirm: "本当に削除してよろしいでしょうか?" }, class: 'btn btn-danger btn-sm' %>
    </div>
  <% end %>
</div>