config/routes.rb
Rails.application.routes.draw do
  get 'reports/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
  resources :users do
    member do 
      get :bookmarks
    end
  end
  
  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :reports, only: [:new, :create]
  resources :picture_details, only: [:index, :new, :create]
  resources :categories, only: [:new, :show, :create]
  resources :areas, only: [:new, :show, :create]
  resources :bookmarks, only: [:index, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
    has_many :post_category_area_relations
    has_many :posts, through: :post_category_area_relations
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user, dependent: :destroy
    validates :name, presence: true, length: { maximum: 15 }
    has_many :post_category_relations, dependent: :destroy
    has_many :posts, through: :post_category_relations
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/picture_detail.rb
class PictureDetail < ApplicationRecord
  belongs_to :post
  validates :image1, presence: true
  mount_uploader :image1, PictureUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, dependent: :destroy
  mount_uploader :picture, PictureUploader
  validates :title, presence: true, length: { maximum: 30 }
  validates :detail, presence: true, length: { maximum: 300 }
  validates :picture, presence: true
  validate :picture_size
  has_many :picture_details, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmark, dependent: :destroy
  has_many :post_category_relations, dependent: :destroy
  has_many :categories, through: :post_category_relations
  has_many :post_category_area_relations, dependent: :destroy
  has_many :area, through: :post_category_area_relations
  geocoded_by :address, latitude: :latitude, longitude: :longitude
  after_validation :geocode, if: :address_changed?

  accepts_nested_attributes_for :post_category_relations, allow_destroy: true

  private
  
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "ファイルサイズを5MB以下にしてください。")
    end
  end
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :picture_details, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :addbookmark, through: :bookmarks, source: :post
  has_many :reverses_of_bookmark, class_name: 'Bookmark', foreign_key: 'user_id'
  has_many :bookmarker, through: :reverses_of_bookmark, source: :user
  
  def bookmark(post)
    self.bookmarks.find_or_create_by(post_id: post.id)
  end
  
  def unbookmark(post)
    bookmark = self.bookmarks.find_by(post_id: post.id)
    bookmark.destroy if bookmark
  end
  
  def bookmark_add?(post)
    self.addbookmark.include?(post)
  end
  
  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def feed_posts
    @posts = Post.all
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
    def show
        @area = Area.find_by(id: params[:id])
        @area_posts = @area.posts.all
        @posts = Post.all.page(params[:page]).page(params[:page]).per(5)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sidebar_link_item(name, path)
        class_name = 'channel'
        class_name << ' active' if current_page?(path)

        content_tag :li, class:class_name do
        link_to name, path, class: 'channel_name'
        end
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    if (user_id = session[:user_id])
      @current_user || User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def logged_in?
    !!current_user
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="container-fluid text-center">
  <div class="text-center　mb-2">
    <div class="row">
      <div class="col-md">
        <%= link_to 'ホーム', root_url, class: 'h6 m-3' %>
        <%= link_to 'よくある質問', root_url, class: 'h6 m-3' %>
        <%= link_to 'お問い合わせ', root_url, class: 'h6 m-3' %>
      </div>
    </div>
  </div>
</div>
<div class="footer-copyright text-center py-2">© 2020 Copyright:
  <a href="https://www.wantedly.com/users/127326700">Takuya Nagai</a>, All Rights Reserved.
</div>

app/views/layouts/_leftsidebar.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h2 class="panel-title">魚種のカテゴリ一覧</h2>
  </div>
	<% @categories.each do |category| %>
		<div class="panel-body">
			<%= link_to "#{category.name}", category_path(category) %>
		</div>
	<% end %>
</div>
<div class="panel panel-primary1">
  <div class="panel-heading">
    <h2 class="panel-title">釣果エリア一覧</h2>
  </div>
  <% @areas.each do |area| %>
	<div class="panel-body">
		<%= link_to "#{area.name}", area_path(area) %>
	</div>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light">
  <a class="navbar-brand" href="/">Fishing Shares</a><i class="fas fa-fish"></i>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if logged_in? %>
        <% if current_user.admin? %> 
          <li class="nav-item"><%= link_to 'お知らせ投稿', new_report_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'カテゴリ追加', new_category_path, class: 'nav-link' %></li>
        <% end %>
          <li class="nav-item"><%= link_to '釣果投稿', new_post_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ユーザ一覧', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">アカウント</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to '設定', edit_user_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to 'ブックマーク', bookmarks_path %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
      <% else %>
        <li class="nav-item"><%= link_to '釣れた魚をシェアする', login_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_rightsidebar.html.erb
<%= javascript_include_tag 'weather.js' %>
<div class="right-sidebar">
    <div id="city-name">
    </div>
    <div id="weather">
    </div>
</div>
    

app/views/layouts/_sidebar.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h2 class="panel-title">魚種のカテゴリ一覧</h2>
  </div>
	<% @categories.each do |category| %>
		<div class="panel-body">
			<%= link_to "#{category.name}", category_path(category) %>
		</div>
	<% end %>
</div>
<div class="panel panel-primary1">
  <div class="panel-heading">
    <h2 class="panel-title">釣果エリア一覧</h2>
  </div>
	<div class="panel-body">
		<%= link_to "北海道", root_path() %>
	</div>
	<div class="panel-body">	
		<%= link_to "東北", root_path() %>
	</div>
	<div class="panel-body">
		<%= link_to "関東", root_path() %>
	</div>
	<div class="panel-body">
		<%= link_to "中部", root_path() %>
	</div>
	<div class="panel-body">
		<%= link_to "近畿", root_path() %>
	</div>
	<div class="panel-body">
		<%= link_to "中国", root_path() %>
	</div>
	<div class="panel-body">	
		<%= link_to "九州", root_path() %>
	</div>
	<div class="panel-body">
		<%= link_to "沖縄", root_path() %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag('fish.ico') %>
    <title>Fishing Shares</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.15/jquery.bxslider.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.0.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.15/jquery.bxslider.min.js"></script>
  </head>
  <body>
    <header class="header">
      <%= render 'layouts/navbar' %>
    </header>

    <div class="container">
      <%= render 'reports/toppage_top' %>
    </div>

    <div class="row">
      <div class="col-2 offset-1">
        <%= render 'layouts/leftsidebar' %>
      </div>
    
      <div class="col-6">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>

      <div class="col-2 offset-right-1">
        <%= render 'layouts/rightsidebar' %>
      </div>
    </div>

    <%= javascript_include_tag 'slider.js' %>
  </body>
  <footer class="page-footer font-small">
    <%= render 'layouts/footer' %>
  </footer>
</html>